#!/usr/bin/env bash
#
# FlowTrace Launcher Script for Node.js
# Generated by FlowTrace CLI v1.0.0
#

set -e

# Load .env file if it exists
if [[ -f .env ]]; then
  export $(grep -v '^#' .env | xargs)
fi

# Configuration
AGENT_PATH=".flowtrace/flowtrace-agent-js/src/loader.js"
PACKAGE_PREFIX="{{PACKAGE_PREFIX}}"
APP_SCRIPT="{{APP_SCRIPT}}"
LOG_FILE="${FLOWTRACE_LOGFILE:-flowtrace.jsonl}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored message
print_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

print_success() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

# Header
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}       FlowTrace Node.js Application Launcher             ${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo

# Check if agent exists
if [[ ! -f "$AGENT_PATH" ]]; then
  print_error "FlowTrace agent not found: $AGENT_PATH"
  echo "Run 'flowtrace init' to install the agent"
  exit 1
fi

print_success "Agent found: $AGENT_PATH"

# Check if application script exists
if [[ ! -f "$APP_SCRIPT" ]]; then
  print_error "Application script not found: $APP_SCRIPT"
  exit 1
fi

print_success "Application script: $APP_SCRIPT"

# Configuration display
echo
print_info "Configuration:"
echo "  Package Prefix: ${PACKAGE_PREFIX:-"(all packages)"}"
echo "  Log File:       $LOG_FILE"
echo "  Application:    $APP_SCRIPT"
echo

# Set environment variables
export FLOWTRACE_LOGFILE="$LOG_FILE"

if [[ -n "$PACKAGE_PREFIX" ]]; then
  export FLOWTRACE_PACKAGE_PREFIX="$PACKAGE_PREFIX"
fi

# Export FLOWTRACE_STDOUT if set
if [[ -n "$FLOWTRACE_STDOUT" ]]; then
  export FLOWTRACE_STDOUT
fi

# Export other FlowTrace configuration
if [[ -n "$FLOWTRACE_MAX_ARG_LENGTH" ]]; then
  export FLOWTRACE_MAX_ARG_LENGTH
fi

if [[ -n "$FLOWTRACE_CAPTURE_STACK" ]]; then
  export FLOWTRACE_CAPTURE_STACK
fi

if [[ -n "$FLOWTRACE_EXCLUDE" ]]; then
  export FLOWTRACE_EXCLUDE
fi

# Convert AGENT_PATH to absolute path for --require
AGENT_ABS_PATH="$(cd "$(dirname "$AGENT_PATH")" && pwd)/$(basename "$AGENT_PATH")"

# Start application
print_info "Starting application with FlowTrace..."
echo

# Detect TypeScript
if [[ "$APP_SCRIPT" == *.ts ]]; then
  print_info "TypeScript detected, using ts-node..."

  # Check if ts-node is available
  if ! command -v ts-node &> /dev/null; then
    print_warning "ts-node not found, installing..."
    npm install --save-dev ts-node typescript @types/node
  fi

  # Run with ts-node
  node --require "$AGENT_ABS_PATH" --require ts-node/register "$APP_SCRIPT" "$@"
else
  # Run regular Node.js
  node --require "$AGENT_ABS_PATH" "$APP_SCRIPT" "$@"
fi
