#
# FlowTrace Launcher Script for Java (PowerShell)
# Generated by FlowTrace CLI v1.0.0
#

$ErrorActionPreference = "Stop"

# Configuration
$AgentPath = ".flowtrace\flowtrace-agent.jar"
$PackagePrefix = "{{PACKAGE_PREFIX}}"
$AppJar = "{{APP_JAR}}"
$LogFile = if ($env:FLOWTRACE_LOGFILE) { $env:FLOWTRACE_LOGFILE } else { "flowtrace.jsonl" }

# Helper functions
function Write-Info($message) {
    Write-Host "ℹ $message" -ForegroundColor Blue
}

function Write-Success($message) {
    Write-Host "✓ $message" -ForegroundColor Green
}

function Write-Error($message) {
    Write-Host "✗ $message" -ForegroundColor Red
}

function Write-Warning($message) {
    Write-Host "⚠ $message" -ForegroundColor Yellow
}

# Header
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Blue
Write-Host "         FlowTrace Java Application Launcher               " -ForegroundColor Blue
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Blue
Write-Host ""

# Check if agent exists
if (-not (Test-Path $AgentPath)) {
    Write-Error "FlowTrace agent not found: $AgentPath"
    Write-Host "Run 'flowtrace init' to install the agent"
    exit 1
}

Write-Success "Agent found: $AgentPath"

# Auto-detect JAR if not specified
if (-not $AppJar) {
    Write-Info "Detecting application JAR..."

    if (-not (Test-Path "target")) {
        Write-Error "target\ directory not found. Have you built the project?"
        Write-Host "Run: mvn clean package"
        exit 1
    }

    $AppJar = Get-ChildItem -Path "target" -Filter "*.jar" -File |
              Where-Object { $_.Name -notlike "*sources*" -and $_.Name -notlike "*javadoc*" } |
              Select-Object -First 1 |
              ForEach-Object { $_.FullName }

    if (-not $AppJar) {
        Write-Error "No JAR found in target\. Please build the project first"
        Write-Host "Run: mvn clean package"
        exit 1
    }

    Write-Success "Found JAR: $AppJar"
}
else {
    if (-not (Test-Path $AppJar)) {
        Write-Error "Specified JAR not found: $AppJar"
        exit 1
    }
    Write-Success "Using JAR: $AppJar"
}

# Configuration display
Write-Host ""
Write-Info "Configuration:"
Write-Host "  Package Prefix: $(if ($PackagePrefix) { $PackagePrefix } else { '(all packages)' })"
Write-Host "  Log File:       $LogFile"
Write-Host "  Application:    $AppJar"
Write-Host ""

# Build Java arguments
$JavaArgs = @(
    "-javaagent:$AgentPath",
    "-Dflowtrace.logfile=$LogFile"
)

# Add package prefix if specified
if ($PackagePrefix) {
    $JavaArgs += "-Dflowtrace.package-prefix=$PackagePrefix"
}

# Add stdout output if enabled
if ($env:FLOWTRACE_STDOUT -eq "true") {
    $JavaArgs += "-Dflowtrace.stdout=true"
}

# Add any additional FlowTrace configuration from environment
if ($env:FLOWTRACE_ANNOTATION_ONLY) {
    $JavaArgs += "-Dflowtrace.annotation-only=$($env:FLOWTRACE_ANNOTATION_ONLY)"
}

if ($env:FLOWTRACE_MAX_ARG_LENGTH) {
    $JavaArgs += "-Dflowtrace.max-arg-length=$($env:FLOWTRACE_MAX_ARG_LENGTH)"
}

if ($env:FLOWTRACE_CAPTURE_STACK) {
    $JavaArgs += "-Dflowtrace.capture-stack=$($env:FLOWTRACE_CAPTURE_STACK)"
}

# Start application
Write-Info "Starting application with FlowTrace..."
Write-Host ""

# Run with FlowTrace
java $JavaArgs -jar $AppJar $args
