#
# FlowTrace Launcher Script for Node.js (PowerShell)
# Generated by FlowTrace CLI v1.0.0
#

$ErrorActionPreference = "Stop"

# Configuration
$AgentPath = ".flowtrace\flowtrace-agent-js\src\loader.js"
$PackagePrefix = "{{PACKAGE_PREFIX}}"
$AppScript = "{{APP_SCRIPT}}"
$LogFile = if ($env:FLOWTRACE_LOGFILE) { $env:FLOWTRACE_LOGFILE } else { "flowtrace.jsonl" }

# Helper functions
function Write-Info($message) {
    Write-Host "ℹ $message" -ForegroundColor Blue
}

function Write-Success($message) {
    Write-Host "✓ $message" -ForegroundColor Green
}

function Write-Error($message) {
    Write-Host "✗ $message" -ForegroundColor Red
}

function Write-Warning($message) {
    Write-Host "⚠ $message" -ForegroundColor Yellow
}

# Header
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Blue
Write-Host "       FlowTrace Node.js Application Launcher             " -ForegroundColor Blue
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Blue
Write-Host ""

# Check if agent exists
if (-not (Test-Path $AgentPath)) {
    Write-Error "FlowTrace agent not found: $AgentPath"
    Write-Host "Run 'flowtrace init' to install the agent"
    exit 1
}

Write-Success "Agent found: $AgentPath"

# Check if application script exists
if (-not (Test-Path $AppScript)) {
    Write-Error "Application script not found: $AppScript"
    exit 1
}

Write-Success "Application script: $AppScript"

# Configuration display
Write-Host ""
Write-Info "Configuration:"
Write-Host "  Package Prefix: $(if ($PackagePrefix) { $PackagePrefix } else { '(all packages)' })"
Write-Host "  Log File:       $LogFile"
Write-Host "  Application:    $AppScript"
Write-Host ""

# Set environment variables
$env:FLOWTRACE_LOGFILE = $LogFile

if ($PackagePrefix) {
    $env:FLOWTRACE_PACKAGE_PREFIX = $PackagePrefix
}

# Detect TypeScript
if ($AppScript -like "*.ts") {
    Write-Info "TypeScript detected, using ts-node..."

    # Check if ts-node is available
    $tsNode = Get-Command ts-node -ErrorAction SilentlyContinue

    if (-not $tsNode) {
        Write-Warning "ts-node not found, installing..."
        npm install --save-dev ts-node typescript @types/node
    }

    # Run with ts-node
    node --require $AgentPath --require ts-node/register $AppScript $args
}
else {
    # Run regular Node.js
    node --require $AgentPath $AppScript $args
}
