#!/usr/bin/env bash
#
# FlowTrace Launcher Script for Java
# Generated by FlowTrace CLI v1.0.0
#

set -e

# Load .env file if it exists
if [[ -f .env ]]; then
  export $(grep -v '^#' .env | xargs)
fi

# Configuration
AGENT_PATH=".flowtrace/flowtrace-agent.jar"
PACKAGE_PREFIX="{{PACKAGE_PREFIX}}"
APP_JAR="{{APP_JAR}}"
LOG_FILE="${FLOWTRACE_LOGFILE:-flowtrace.jsonl}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored message
print_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

print_success() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

# Header
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}         FlowTrace Java Application Launcher               ${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo

# Check if agent exists
if [[ ! -f "$AGENT_PATH" ]]; then
  print_error "FlowTrace agent not found: $AGENT_PATH"
  echo "Run 'flowtrace init' to install the agent"
  exit 1
fi

print_success "Agent found: $AGENT_PATH"

# Auto-detect JAR if not specified
if [[ -z "$APP_JAR" ]]; then
  print_info "Detecting application JAR..."

  if [[ ! -d "target" ]]; then
    print_error "target/ directory not found. Have you built the project?"
    echo "Run: mvn clean package"
    exit 1
  fi

  APP_JAR=$(find target -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -1)

  if [[ -z "$APP_JAR" ]]; then
    print_error "No JAR found in target/. Please build the project first"
    echo "Run: mvn clean package"
    exit 1
  fi

  print_success "Found JAR: $APP_JAR"
else
  if [[ ! -f "$APP_JAR" ]]; then
    print_error "Specified JAR not found: $APP_JAR"
    exit 1
  fi
  print_success "Using JAR: $APP_JAR"
fi

# Configuration display
echo
print_info "Configuration:"
echo "  Package Prefix: ${PACKAGE_PREFIX:-"(all packages)"}"
echo "  Log File:       $LOG_FILE"
echo "  Application:    $APP_JAR"
echo

# Build Java arguments
JAVA_ARGS=(
  "-javaagent:$AGENT_PATH"
  "-Dflowtrace.logfile=$LOG_FILE"
)

# Add package prefix if specified
if [[ -n "$PACKAGE_PREFIX" ]]; then
  JAVA_ARGS+=("-Dflowtrace.package-prefix=$PACKAGE_PREFIX")
fi

# Add stdout output if enabled
if [[ "$FLOWTRACE_STDOUT" == "true" ]]; then
  JAVA_ARGS+=("-Dflowtrace.stdout=true")
fi

# Add any additional FlowTrace configuration from environment
if [[ -n "$FLOWTRACE_ANNOTATION_ONLY" ]]; then
  JAVA_ARGS+=("-Dflowtrace.annotation-only=$FLOWTRACE_ANNOTATION_ONLY")
fi

if [[ -n "$FLOWTRACE_MAX_ARG_LENGTH" ]]; then
  JAVA_ARGS+=("-Dflowtrace.max-arg-length=$FLOWTRACE_MAX_ARG_LENGTH")
fi

if [[ -n "$FLOWTRACE_CAPTURE_STACK" ]]; then
  JAVA_ARGS+=("-Dflowtrace.capture-stack=$FLOWTRACE_CAPTURE_STACK")
fi

# Start application
print_info "Starting application with FlowTrace..."
echo

# Run with FlowTrace
java "${JAVA_ARGS[@]}" -jar "$APP_JAR" "$@"
